// Copyright (c) 2026, Dev kaffah
// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct PipInitRequest: Hashable, CustomStringConvertible {
  var enabled: Bool
  var disableWhenScreenSharing: Bool
  var androidAutoEnterOnBackground: Bool
  var iosAutoEnterOnBackground: Bool
  var iosIncludeLocalParticipantVideo: Bool
  var videoWidth: Int64
  var videoHeight: Int64
  var iosMirrorSelfView: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipInitRequest? {
    let enabled = pigeonVar_list[0] as! Bool
    let disableWhenScreenSharing = pigeonVar_list[1] as! Bool
    let androidAutoEnterOnBackground = pigeonVar_list[2] as! Bool
    let iosAutoEnterOnBackground = pigeonVar_list[3] as! Bool
    let iosIncludeLocalParticipantVideo = pigeonVar_list[4] as! Bool
    let videoWidth = pigeonVar_list[5] as! Int64
    let videoHeight = pigeonVar_list[6] as! Int64
    let iosMirrorSelfView = pigeonVar_list[7] as! Bool

    return PipInitRequest(
      enabled: enabled,
      disableWhenScreenSharing: disableWhenScreenSharing,
      androidAutoEnterOnBackground: androidAutoEnterOnBackground,
      iosAutoEnterOnBackground: iosAutoEnterOnBackground,
      iosIncludeLocalParticipantVideo: iosIncludeLocalParticipantVideo,
      videoWidth: videoWidth,
      videoHeight: videoHeight,
      iosMirrorSelfView: iosMirrorSelfView
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      disableWhenScreenSharing,
      androidAutoEnterOnBackground,
      iosAutoEnterOnBackground,
      iosIncludeLocalParticipantVideo,
      videoWidth,
      videoHeight,
      iosMirrorSelfView,
    ]
  }
  static func == (lhs: PipInitRequest, rhs: PipInitRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MessagesPigeonInternal.deepEquals(lhs.disableWhenScreenSharing, rhs.disableWhenScreenSharing) && MessagesPigeonInternal.deepEquals(lhs.androidAutoEnterOnBackground, rhs.androidAutoEnterOnBackground) && MessagesPigeonInternal.deepEquals(lhs.iosAutoEnterOnBackground, rhs.iosAutoEnterOnBackground) && MessagesPigeonInternal.deepEquals(lhs.iosIncludeLocalParticipantVideo, rhs.iosIncludeLocalParticipantVideo) && MessagesPigeonInternal.deepEquals(lhs.videoWidth, rhs.videoWidth) && MessagesPigeonInternal.deepEquals(lhs.videoHeight, rhs.videoHeight) && MessagesPigeonInternal.deepEquals(lhs.iosMirrorSelfView, rhs.iosMirrorSelfView)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PipInitRequest")
    MessagesPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: disableWhenScreenSharing, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidAutoEnterOnBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: iosAutoEnterOnBackground, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: iosIncludeLocalParticipantVideo, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: iosMirrorSelfView, hasher: &hasher)
  }

  public var description: String {
    return "PipInitRequest(enabled: \(String(describing: enabled)), disableWhenScreenSharing: \(String(describing: disableWhenScreenSharing)), androidAutoEnterOnBackground: \(String(describing: androidAutoEnterOnBackground)), iosAutoEnterOnBackground: \(String(describing: iosAutoEnterOnBackground)), iosIncludeLocalParticipantVideo: \(String(describing: iosIncludeLocalParticipantVideo)), videoWidth: \(String(describing: videoWidth)), videoHeight: \(String(describing: videoHeight)), iosMirrorSelfView: \(String(describing: iosMirrorSelfView)))"
  }
}

/// One tile of the PiP window.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PipParticipant: Hashable, CustomStringConvertible {
  var identity: String
  var isLocal: Bool
  /// Null while the camera is off, unpublished, or unsubscribed.
  var videoTrackId: String? = nil
  var isMicMuted: Bool
  var displayName: String
  var avatarUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipParticipant? {
    let identity = pigeonVar_list[0] as! String
    let isLocal = pigeonVar_list[1] as! Bool
    let videoTrackId: String? = nilOrValue(pigeonVar_list[2])
    let isMicMuted = pigeonVar_list[3] as! Bool
    let displayName = pigeonVar_list[4] as! String
    let avatarUrl: String? = nilOrValue(pigeonVar_list[5])

    return PipParticipant(
      identity: identity,
      isLocal: isLocal,
      videoTrackId: videoTrackId,
      isMicMuted: isMicMuted,
      displayName: displayName,
      avatarUrl: avatarUrl
    )
  }
  func toList() -> [Any?] {
    return [
      identity,
      isLocal,
      videoTrackId,
      isMicMuted,
      displayName,
      avatarUrl,
    ]
  }
  static func == (lhs: PipParticipant, rhs: PipParticipant) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.identity, rhs.identity) && MessagesPigeonInternal.deepEquals(lhs.isLocal, rhs.isLocal) && MessagesPigeonInternal.deepEquals(lhs.videoTrackId, rhs.videoTrackId) && MessagesPigeonInternal.deepEquals(lhs.isMicMuted, rhs.isMicMuted) && MessagesPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && MessagesPigeonInternal.deepEquals(lhs.avatarUrl, rhs.avatarUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PipParticipant")
    MessagesPigeonInternal.deepHash(value: identity, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isLocal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoTrackId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isMicMuted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: avatarUrl, hasher: &hasher)
  }

  public var description: String {
    return "PipParticipant(identity: \(String(describing: identity)), isLocal: \(String(describing: isLocal)), videoTrackId: \(String(describing: videoTrackId)), isMicMuted: \(String(describing: isMicMuted)), displayName: \(String(describing: displayName)), avatarUrl: \(String(describing: avatarUrl)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PipInitRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return PipParticipant.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PipInitRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PipParticipant {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiveKitPipHostApi {
  func initialize(request: PipInitRequest) throws
  func enterPip() throws
  func exitPip() throws
  func dispose() throws
  func isSupported() throws -> Bool
  func updateActiveTrack(trackId: String) throws
  /// Tiles of the PiP window: the remote speaker and the local camera.
  func updateParticipants(participants: [PipParticipant]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiveKitPipHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LiveKitPipHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiveKitPipHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PipInitRequest
        do {
          try api.initialize(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let enterPipChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.enterPip\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enterPipChannel.setMessageHandler { _, reply in
        do {
          try api.enterPip()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enterPipChannel.setMessageHandler(nil)
    }
    let exitPipChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.exitPip\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exitPipChannel.setMessageHandler { _, reply in
        do {
          try api.exitPip()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exitPipChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let updateActiveTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.updateActiveTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateActiveTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let trackIdArg = args[0] as! String
        do {
          try api.updateActiveTrack(trackId: trackIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateActiveTrackChannel.setMessageHandler(nil)
    }
    /// Tiles of the PiP window: the remote speaker and the local camera.
    let updateParticipantsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.updateParticipants\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateParticipantsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let participantsArg = args[0] as! [PipParticipant]
        do {
          try api.updateParticipants(participants: participantsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateParticipantsChannel.setMessageHandler(nil)
    }
  }
}
