// Copyright (c) 2026, Dev kaffah
// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class PipInitRequest {
  PipInitRequest({
    this.enabled = true,
    this.disableWhenScreenSharing = true,
    this.androidAutoEnterOnBackground = true,
    this.iosAutoEnterOnBackground = true,
    this.iosIncludeLocalParticipantVideo = true,
    this.videoWidth = 0,
    this.videoHeight = 0,
    this.iosMirrorSelfView = true,
  });

  bool enabled;

  bool disableWhenScreenSharing;

  bool androidAutoEnterOnBackground;

  bool iosAutoEnterOnBackground;

  bool iosIncludeLocalParticipantVideo;

  int videoWidth;

  int videoHeight;

  bool iosMirrorSelfView;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      disableWhenScreenSharing,
      androidAutoEnterOnBackground,
      iosAutoEnterOnBackground,
      iosIncludeLocalParticipantVideo,
      videoWidth,
      videoHeight,
      iosMirrorSelfView,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PipInitRequest decode(Object result) {
    result as List<Object?>;
    return PipInitRequest(
      enabled: result[0]! as bool,
      disableWhenScreenSharing: result[1]! as bool,
      androidAutoEnterOnBackground: result[2]! as bool,
      iosAutoEnterOnBackground: result[3]! as bool,
      iosIncludeLocalParticipantVideo: result[4]! as bool,
      videoWidth: result[5]! as int,
      videoHeight: result[6]! as int,
      iosMirrorSelfView: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PipInitRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enabled, other.enabled) &&
        _deepEquals(disableWhenScreenSharing, other.disableWhenScreenSharing) &&
        _deepEquals(
          androidAutoEnterOnBackground,
          other.androidAutoEnterOnBackground,
        ) &&
        _deepEquals(iosAutoEnterOnBackground, other.iosAutoEnterOnBackground) &&
        _deepEquals(
          iosIncludeLocalParticipantVideo,
          other.iosIncludeLocalParticipantVideo,
        ) &&
        _deepEquals(videoWidth, other.videoWidth) &&
        _deepEquals(videoHeight, other.videoHeight) &&
        _deepEquals(iosMirrorSelfView, other.iosMirrorSelfView);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PipInitRequest(enabled: $enabled, disableWhenScreenSharing: $disableWhenScreenSharing, androidAutoEnterOnBackground: $androidAutoEnterOnBackground, iosAutoEnterOnBackground: $iosAutoEnterOnBackground, iosIncludeLocalParticipantVideo: $iosIncludeLocalParticipantVideo, videoWidth: $videoWidth, videoHeight: $videoHeight, iosMirrorSelfView: $iosMirrorSelfView)';
  }
}

/// One tile of the PiP window.
class PipParticipant {
  PipParticipant({
    required this.identity,
    required this.isLocal,
    this.videoTrackId,
    required this.isMicMuted,
    required this.displayName,
    this.avatarUrl,
  });

  String identity;

  bool isLocal;

  /// Null while the camera is off, unpublished, or unsubscribed.
  String? videoTrackId;

  bool isMicMuted;

  String displayName;

  String? avatarUrl;

  List<Object?> _toList() {
    return <Object?>[
      identity,
      isLocal,
      videoTrackId,
      isMicMuted,
      displayName,
      avatarUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PipParticipant decode(Object result) {
    result as List<Object?>;
    return PipParticipant(
      identity: result[0]! as String,
      isLocal: result[1]! as bool,
      videoTrackId: result[2] as String?,
      isMicMuted: result[3]! as bool,
      displayName: result[4]! as String,
      avatarUrl: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PipParticipant || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(identity, other.identity) &&
        _deepEquals(isLocal, other.isLocal) &&
        _deepEquals(videoTrackId, other.videoTrackId) &&
        _deepEquals(isMicMuted, other.isMicMuted) &&
        _deepEquals(displayName, other.displayName) &&
        _deepEquals(avatarUrl, other.avatarUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PipParticipant(identity: $identity, isLocal: $isLocal, videoTrackId: $videoTrackId, isMicMuted: $isMicMuted, displayName: $displayName, avatarUrl: $avatarUrl)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PipInitRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PipParticipant) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PipInitRequest.decode(readValue(buffer)!);
      case 130:
        return PipParticipant.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LiveKitPipHostApi {
  /// Constructor for [LiveKitPipHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LiveKitPipHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(PipInitRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> enterPip() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.enterPip$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> exitPip() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.exitPip$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> updateActiveTrack(String trackId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.updateActiveTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[trackId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Tiles of the PiP window: the remote speaker and the local camera.
  Future<void> updateParticipants(List<PipParticipant> participants) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.livekit_pip_ios.LiveKitPipHostApi.updateParticipants$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[participants],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
